name: Run all tests

on:
  push:
    branches: [ main, test_branch ]
  pull_request:
    branches: [ main, test_branch ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean install the project
        run: npm ci


          
      - name: Execute all tests
        run: npm test
        env: 
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          APPLITOOLS_BATCH_ID: ${{ github.event.pull_request.head.sha || github.sha }}
      
      - name: Make API Call to Fetch Data
        id: fetch_data
        run: |
          response=$(curl -s "https://eyes.applitools.com/api/sessions/batches/${{ github.event.pull_request.head.sha || github.sha }}/bypointerid?apiKey=${{ secrets.APPLITOOLS_API_KEY }}")
          echo "$response" > response.json
          id=$(jq -r '.id' response.json)
          echo "::set-output name=id::$id"

      - name: Create Comment
        run: |
          # Use GitHub API to create a comment on the PR
          BATCH_ID=${{ steps.fetch_data.outputs.id }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="<html><head></head><body><h1>Hello World!</h1><a href='https://www.google.com'><img src='https://eyes.applitools.com/app/test-results/${BATCH_ID}'></a></body></html>"
          GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"

