name: Run all tests

on:
  push:
    branches: [ main, test_branch ]
  pull_request:
    branches: [ main, test_branch ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out project
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Clean install the project
        run: npm ci

      - name: Create Comment
        run: |
          # Use GitHub API to create a comment on the PR
          PR_NUMBER=${{ github.event.pull_request.number }}
          COMMENT="<html>
<head></head>
<body>
   <a href = 'https://www.google.com'><img src = 'https://debug.to/?qa=blob&qa_blobid=5900171906946478750'></a>
</body>
</html>"
          GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}
          COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"

      - name: Execute all tests
        run: npm test
        env: 
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

